import { TypeIsActive } from "../enums/type-active.enum";

export interface IProduct {
    // id: number,
    productName: string,
    weight: number,
    cannabisWeight: number,
    price: number,
    fee: number,
    sku?: string,
    imageURL?: string,
    barcode?: string,
    description?: string,
    cannabisVolume?: number,
    isActive?: TypeIsActive,
    createDate?: String,
    updateDate?: String,
    fullProductName?: string,
    productSlug?: string,
    salesPrice: number,
    inventory: number,
    discountAmount: number,
    productscol?: string,
    categories_id?: number,
    supplier_id?: number,
    tenant_id?: number,
    retailer_id?: number,
    discount_id?: number,
    parentProduct_id?: number,
}